// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: student.proto

package com.mastercard.protobuf;

public final class StudentProto {
  private StudentProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface StudentOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Student)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 grade = 1;</code>
     */
    int getGrade();

    /**
     * <code>repeated .Student.SchoolSubject enrolled = 2;</code>
     */
    java.util.List<com.mastercard.protobuf.StudentProto.Student.SchoolSubject> 
        getEnrolledList();
    /**
     * <code>repeated .Student.SchoolSubject enrolled = 2;</code>
     */
    com.mastercard.protobuf.StudentProto.Student.SchoolSubject getEnrolled(int index);
    /**
     * <code>repeated .Student.SchoolSubject enrolled = 2;</code>
     */
    int getEnrolledCount();
    /**
     * <code>repeated .Student.SchoolSubject enrolled = 2;</code>
     */
    java.util.List<? extends com.mastercard.protobuf.StudentProto.Student.SchoolSubjectOrBuilder> 
        getEnrolledOrBuilderList();
    /**
     * <code>repeated .Student.SchoolSubject enrolled = 2;</code>
     */
    com.mastercard.protobuf.StudentProto.Student.SchoolSubjectOrBuilder getEnrolledOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code Student}
   */
  public  static final class Student extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Student)
      StudentOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Student.newBuilder() to construct.
    private Student(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Student() {
      enrolled_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Student(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              grade_ = input.readInt32();
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) != 0)) {
                enrolled_ = new java.util.ArrayList<com.mastercard.protobuf.StudentProto.Student.SchoolSubject>();
                mutable_bitField0_ |= 0x00000002;
              }
              enrolled_.add(
                  input.readMessage(com.mastercard.protobuf.StudentProto.Student.SchoolSubject.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) != 0)) {
          enrolled_ = java.util.Collections.unmodifiableList(enrolled_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.mastercard.protobuf.StudentProto.internal_static_Student_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.mastercard.protobuf.StudentProto.internal_static_Student_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.mastercard.protobuf.StudentProto.Student.class, com.mastercard.protobuf.StudentProto.Student.Builder.class);
    }

    public interface SchoolSubjectOrBuilder extends
        // @@protoc_insertion_point(interface_extends:Student.SchoolSubject)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>string name = 1;</code>
       */
      java.lang.String getName();
      /**
       * <code>string name = 1;</code>
       */
      com.google.protobuf.ByteString
          getNameBytes();

      /**
       * <code>int32 classroom = 2;</code>
       */
      int getClassroom();
    }
    /**
     * Protobuf type {@code Student.SchoolSubject}
     */
    public  static final class SchoolSubject extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:Student.SchoolSubject)
        SchoolSubjectOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use SchoolSubject.newBuilder() to construct.
      private SchoolSubject(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private SchoolSubject() {
        name_ = "";
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private SchoolSubject(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                java.lang.String s = input.readStringRequireUtf8();

                name_ = s;
                break;
              }
              case 16: {

                classroom_ = input.readInt32();
                break;
              }
              default: {
                if (!parseUnknownField(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.mastercard.protobuf.StudentProto.internal_static_Student_SchoolSubject_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.mastercard.protobuf.StudentProto.internal_static_Student_SchoolSubject_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.mastercard.protobuf.StudentProto.Student.SchoolSubject.class, com.mastercard.protobuf.StudentProto.Student.SchoolSubject.Builder.class);
      }

      public static final int NAME_FIELD_NUMBER = 1;
      private volatile java.lang.Object name_;
      /**
       * <code>string name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        }
      }
      /**
       * <code>string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int CLASSROOM_FIELD_NUMBER = 2;
      private int classroom_;
      /**
       * <code>int32 classroom = 2;</code>
       */
      public int getClassroom() {
        return classroom_;
      }

      private byte memoizedIsInitialized = -1;
      @java.lang.Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      @java.lang.Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (!getNameBytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
        }
        if (classroom_ != 0) {
          output.writeInt32(2, classroom_);
        }
        unknownFields.writeTo(output);
      }

      @java.lang.Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (!getNameBytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
        }
        if (classroom_ != 0) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(2, classroom_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof com.mastercard.protobuf.StudentProto.Student.SchoolSubject)) {
          return super.equals(obj);
        }
        com.mastercard.protobuf.StudentProto.Student.SchoolSubject other = (com.mastercard.protobuf.StudentProto.Student.SchoolSubject) obj;

        if (!getName()
            .equals(other.getName())) return false;
        if (getClassroom()
            != other.getClassroom()) return false;
        if (!unknownFields.equals(other.unknownFields)) return false;
        return true;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + NAME_FIELD_NUMBER;
        hash = (53 * hash) + getName().hashCode();
        hash = (37 * hash) + CLASSROOM_FIELD_NUMBER;
        hash = (53 * hash) + getClassroom();
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static com.mastercard.protobuf.StudentProto.Student.SchoolSubject parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.mastercard.protobuf.StudentProto.Student.SchoolSubject parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.mastercard.protobuf.StudentProto.Student.SchoolSubject parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.mastercard.protobuf.StudentProto.Student.SchoolSubject parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.mastercard.protobuf.StudentProto.Student.SchoolSubject parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.mastercard.protobuf.StudentProto.Student.SchoolSubject parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.mastercard.protobuf.StudentProto.Student.SchoolSubject parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static com.mastercard.protobuf.StudentProto.Student.SchoolSubject parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static com.mastercard.protobuf.StudentProto.Student.SchoolSubject parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static com.mastercard.protobuf.StudentProto.Student.SchoolSubject parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static com.mastercard.protobuf.StudentProto.Student.SchoolSubject parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static com.mastercard.protobuf.StudentProto.Student.SchoolSubject parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @java.lang.Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(com.mastercard.protobuf.StudentProto.Student.SchoolSubject prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @java.lang.Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code Student.SchoolSubject}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:Student.SchoolSubject)
          com.mastercard.protobuf.StudentProto.Student.SchoolSubjectOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.mastercard.protobuf.StudentProto.internal_static_Student_SchoolSubject_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.mastercard.protobuf.StudentProto.internal_static_Student_SchoolSubject_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  com.mastercard.protobuf.StudentProto.Student.SchoolSubject.class, com.mastercard.protobuf.StudentProto.Student.SchoolSubject.Builder.class);
        }

        // Construct using com.mastercard.protobuf.StudentProto.Student.SchoolSubject.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        @java.lang.Override
        public Builder clear() {
          super.clear();
          name_ = "";

          classroom_ = 0;

          return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.mastercard.protobuf.StudentProto.internal_static_Student_SchoolSubject_descriptor;
        }

        @java.lang.Override
        public com.mastercard.protobuf.StudentProto.Student.SchoolSubject getDefaultInstanceForType() {
          return com.mastercard.protobuf.StudentProto.Student.SchoolSubject.getDefaultInstance();
        }

        @java.lang.Override
        public com.mastercard.protobuf.StudentProto.Student.SchoolSubject build() {
          com.mastercard.protobuf.StudentProto.Student.SchoolSubject result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @java.lang.Override
        public com.mastercard.protobuf.StudentProto.Student.SchoolSubject buildPartial() {
          com.mastercard.protobuf.StudentProto.Student.SchoolSubject result = new com.mastercard.protobuf.StudentProto.Student.SchoolSubject(this);
          result.name_ = name_;
          result.classroom_ = classroom_;
          onBuilt();
          return result;
        }

        @java.lang.Override
        public Builder clone() {
          return super.clone();
        }
        @java.lang.Override
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.setField(field, value);
        }
        @java.lang.Override
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return super.clearField(field);
        }
        @java.lang.Override
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return super.clearOneof(oneof);
        }
        @java.lang.Override
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return super.setRepeatedField(field, index, value);
        }
        @java.lang.Override
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.addRepeatedField(field, value);
        }
        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.mastercard.protobuf.StudentProto.Student.SchoolSubject) {
            return mergeFrom((com.mastercard.protobuf.StudentProto.Student.SchoolSubject)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(com.mastercard.protobuf.StudentProto.Student.SchoolSubject other) {
          if (other == com.mastercard.protobuf.StudentProto.Student.SchoolSubject.getDefaultInstance()) return this;
          if (!other.getName().isEmpty()) {
            name_ = other.name_;
            onChanged();
          }
          if (other.getClassroom() != 0) {
            setClassroom(other.getClassroom());
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
          return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.mastercard.protobuf.StudentProto.Student.SchoolSubject parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (com.mastercard.protobuf.StudentProto.Student.SchoolSubject) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }

        private java.lang.Object name_ = "";
        /**
         * <code>string name = 1;</code>
         */
        public java.lang.String getName() {
          java.lang.Object ref = name_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            name_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>string name = 1;</code>
         */
        public com.google.protobuf.ByteString
            getNameBytes() {
          java.lang.Object ref = name_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            name_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string name = 1;</code>
         */
        public Builder setName(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          name_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>string name = 1;</code>
         */
        public Builder clearName() {
          
          name_ = getDefaultInstance().getName();
          onChanged();
          return this;
        }
        /**
         * <code>string name = 1;</code>
         */
        public Builder setNameBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          name_ = value;
          onChanged();
          return this;
        }

        private int classroom_ ;
        /**
         * <code>int32 classroom = 2;</code>
         */
        public int getClassroom() {
          return classroom_;
        }
        /**
         * <code>int32 classroom = 2;</code>
         */
        public Builder setClassroom(int value) {
          
          classroom_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>int32 classroom = 2;</code>
         */
        public Builder clearClassroom() {
          
          classroom_ = 0;
          onChanged();
          return this;
        }
        @java.lang.Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:Student.SchoolSubject)
      }

      // @@protoc_insertion_point(class_scope:Student.SchoolSubject)
      private static final com.mastercard.protobuf.StudentProto.Student.SchoolSubject DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new com.mastercard.protobuf.StudentProto.Student.SchoolSubject();
      }

      public static com.mastercard.protobuf.StudentProto.Student.SchoolSubject getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<SchoolSubject>
          PARSER = new com.google.protobuf.AbstractParser<SchoolSubject>() {
        @java.lang.Override
        public SchoolSubject parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new SchoolSubject(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<SchoolSubject> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<SchoolSubject> getParserForType() {
        return PARSER;
      }

      @java.lang.Override
      public com.mastercard.protobuf.StudentProto.Student.SchoolSubject getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    private int bitField0_;
    public static final int GRADE_FIELD_NUMBER = 1;
    private int grade_;
    /**
     * <code>int32 grade = 1;</code>
     */
    public int getGrade() {
      return grade_;
    }

    public static final int ENROLLED_FIELD_NUMBER = 2;
    private java.util.List<com.mastercard.protobuf.StudentProto.Student.SchoolSubject> enrolled_;
    /**
     * <code>repeated .Student.SchoolSubject enrolled = 2;</code>
     */
    public java.util.List<com.mastercard.protobuf.StudentProto.Student.SchoolSubject> getEnrolledList() {
      return enrolled_;
    }
    /**
     * <code>repeated .Student.SchoolSubject enrolled = 2;</code>
     */
    public java.util.List<? extends com.mastercard.protobuf.StudentProto.Student.SchoolSubjectOrBuilder> 
        getEnrolledOrBuilderList() {
      return enrolled_;
    }
    /**
     * <code>repeated .Student.SchoolSubject enrolled = 2;</code>
     */
    public int getEnrolledCount() {
      return enrolled_.size();
    }
    /**
     * <code>repeated .Student.SchoolSubject enrolled = 2;</code>
     */
    public com.mastercard.protobuf.StudentProto.Student.SchoolSubject getEnrolled(int index) {
      return enrolled_.get(index);
    }
    /**
     * <code>repeated .Student.SchoolSubject enrolled = 2;</code>
     */
    public com.mastercard.protobuf.StudentProto.Student.SchoolSubjectOrBuilder getEnrolledOrBuilder(
        int index) {
      return enrolled_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (grade_ != 0) {
        output.writeInt32(1, grade_);
      }
      for (int i = 0; i < enrolled_.size(); i++) {
        output.writeMessage(2, enrolled_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (grade_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, grade_);
      }
      for (int i = 0; i < enrolled_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, enrolled_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.mastercard.protobuf.StudentProto.Student)) {
        return super.equals(obj);
      }
      com.mastercard.protobuf.StudentProto.Student other = (com.mastercard.protobuf.StudentProto.Student) obj;

      if (getGrade()
          != other.getGrade()) return false;
      if (!getEnrolledList()
          .equals(other.getEnrolledList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + GRADE_FIELD_NUMBER;
      hash = (53 * hash) + getGrade();
      if (getEnrolledCount() > 0) {
        hash = (37 * hash) + ENROLLED_FIELD_NUMBER;
        hash = (53 * hash) + getEnrolledList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.mastercard.protobuf.StudentProto.Student parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mastercard.protobuf.StudentProto.Student parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mastercard.protobuf.StudentProto.Student parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mastercard.protobuf.StudentProto.Student parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mastercard.protobuf.StudentProto.Student parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mastercard.protobuf.StudentProto.Student parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mastercard.protobuf.StudentProto.Student parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.mastercard.protobuf.StudentProto.Student parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.mastercard.protobuf.StudentProto.Student parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.mastercard.protobuf.StudentProto.Student parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.mastercard.protobuf.StudentProto.Student parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.mastercard.protobuf.StudentProto.Student parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.mastercard.protobuf.StudentProto.Student prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Student}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Student)
        com.mastercard.protobuf.StudentProto.StudentOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.mastercard.protobuf.StudentProto.internal_static_Student_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.mastercard.protobuf.StudentProto.internal_static_Student_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.mastercard.protobuf.StudentProto.Student.class, com.mastercard.protobuf.StudentProto.Student.Builder.class);
      }

      // Construct using com.mastercard.protobuf.StudentProto.Student.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getEnrolledFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        grade_ = 0;

        if (enrolledBuilder_ == null) {
          enrolled_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          enrolledBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.mastercard.protobuf.StudentProto.internal_static_Student_descriptor;
      }

      @java.lang.Override
      public com.mastercard.protobuf.StudentProto.Student getDefaultInstanceForType() {
        return com.mastercard.protobuf.StudentProto.Student.getDefaultInstance();
      }

      @java.lang.Override
      public com.mastercard.protobuf.StudentProto.Student build() {
        com.mastercard.protobuf.StudentProto.Student result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.mastercard.protobuf.StudentProto.Student buildPartial() {
        com.mastercard.protobuf.StudentProto.Student result = new com.mastercard.protobuf.StudentProto.Student(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.grade_ = grade_;
        if (enrolledBuilder_ == null) {
          if (((bitField0_ & 0x00000002) != 0)) {
            enrolled_ = java.util.Collections.unmodifiableList(enrolled_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.enrolled_ = enrolled_;
        } else {
          result.enrolled_ = enrolledBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.mastercard.protobuf.StudentProto.Student) {
          return mergeFrom((com.mastercard.protobuf.StudentProto.Student)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.mastercard.protobuf.StudentProto.Student other) {
        if (other == com.mastercard.protobuf.StudentProto.Student.getDefaultInstance()) return this;
        if (other.getGrade() != 0) {
          setGrade(other.getGrade());
        }
        if (enrolledBuilder_ == null) {
          if (!other.enrolled_.isEmpty()) {
            if (enrolled_.isEmpty()) {
              enrolled_ = other.enrolled_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureEnrolledIsMutable();
              enrolled_.addAll(other.enrolled_);
            }
            onChanged();
          }
        } else {
          if (!other.enrolled_.isEmpty()) {
            if (enrolledBuilder_.isEmpty()) {
              enrolledBuilder_.dispose();
              enrolledBuilder_ = null;
              enrolled_ = other.enrolled_;
              bitField0_ = (bitField0_ & ~0x00000002);
              enrolledBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getEnrolledFieldBuilder() : null;
            } else {
              enrolledBuilder_.addAllMessages(other.enrolled_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.mastercard.protobuf.StudentProto.Student parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.mastercard.protobuf.StudentProto.Student) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int grade_ ;
      /**
       * <code>int32 grade = 1;</code>
       */
      public int getGrade() {
        return grade_;
      }
      /**
       * <code>int32 grade = 1;</code>
       */
      public Builder setGrade(int value) {
        
        grade_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 grade = 1;</code>
       */
      public Builder clearGrade() {
        
        grade_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<com.mastercard.protobuf.StudentProto.Student.SchoolSubject> enrolled_ =
        java.util.Collections.emptyList();
      private void ensureEnrolledIsMutable() {
        if (!((bitField0_ & 0x00000002) != 0)) {
          enrolled_ = new java.util.ArrayList<com.mastercard.protobuf.StudentProto.Student.SchoolSubject>(enrolled_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.mastercard.protobuf.StudentProto.Student.SchoolSubject, com.mastercard.protobuf.StudentProto.Student.SchoolSubject.Builder, com.mastercard.protobuf.StudentProto.Student.SchoolSubjectOrBuilder> enrolledBuilder_;

      /**
       * <code>repeated .Student.SchoolSubject enrolled = 2;</code>
       */
      public java.util.List<com.mastercard.protobuf.StudentProto.Student.SchoolSubject> getEnrolledList() {
        if (enrolledBuilder_ == null) {
          return java.util.Collections.unmodifiableList(enrolled_);
        } else {
          return enrolledBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Student.SchoolSubject enrolled = 2;</code>
       */
      public int getEnrolledCount() {
        if (enrolledBuilder_ == null) {
          return enrolled_.size();
        } else {
          return enrolledBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Student.SchoolSubject enrolled = 2;</code>
       */
      public com.mastercard.protobuf.StudentProto.Student.SchoolSubject getEnrolled(int index) {
        if (enrolledBuilder_ == null) {
          return enrolled_.get(index);
        } else {
          return enrolledBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Student.SchoolSubject enrolled = 2;</code>
       */
      public Builder setEnrolled(
          int index, com.mastercard.protobuf.StudentProto.Student.SchoolSubject value) {
        if (enrolledBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureEnrolledIsMutable();
          enrolled_.set(index, value);
          onChanged();
        } else {
          enrolledBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Student.SchoolSubject enrolled = 2;</code>
       */
      public Builder setEnrolled(
          int index, com.mastercard.protobuf.StudentProto.Student.SchoolSubject.Builder builderForValue) {
        if (enrolledBuilder_ == null) {
          ensureEnrolledIsMutable();
          enrolled_.set(index, builderForValue.build());
          onChanged();
        } else {
          enrolledBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Student.SchoolSubject enrolled = 2;</code>
       */
      public Builder addEnrolled(com.mastercard.protobuf.StudentProto.Student.SchoolSubject value) {
        if (enrolledBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureEnrolledIsMutable();
          enrolled_.add(value);
          onChanged();
        } else {
          enrolledBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Student.SchoolSubject enrolled = 2;</code>
       */
      public Builder addEnrolled(
          int index, com.mastercard.protobuf.StudentProto.Student.SchoolSubject value) {
        if (enrolledBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureEnrolledIsMutable();
          enrolled_.add(index, value);
          onChanged();
        } else {
          enrolledBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Student.SchoolSubject enrolled = 2;</code>
       */
      public Builder addEnrolled(
          com.mastercard.protobuf.StudentProto.Student.SchoolSubject.Builder builderForValue) {
        if (enrolledBuilder_ == null) {
          ensureEnrolledIsMutable();
          enrolled_.add(builderForValue.build());
          onChanged();
        } else {
          enrolledBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Student.SchoolSubject enrolled = 2;</code>
       */
      public Builder addEnrolled(
          int index, com.mastercard.protobuf.StudentProto.Student.SchoolSubject.Builder builderForValue) {
        if (enrolledBuilder_ == null) {
          ensureEnrolledIsMutable();
          enrolled_.add(index, builderForValue.build());
          onChanged();
        } else {
          enrolledBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Student.SchoolSubject enrolled = 2;</code>
       */
      public Builder addAllEnrolled(
          java.lang.Iterable<? extends com.mastercard.protobuf.StudentProto.Student.SchoolSubject> values) {
        if (enrolledBuilder_ == null) {
          ensureEnrolledIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, enrolled_);
          onChanged();
        } else {
          enrolledBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Student.SchoolSubject enrolled = 2;</code>
       */
      public Builder clearEnrolled() {
        if (enrolledBuilder_ == null) {
          enrolled_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          enrolledBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Student.SchoolSubject enrolled = 2;</code>
       */
      public Builder removeEnrolled(int index) {
        if (enrolledBuilder_ == null) {
          ensureEnrolledIsMutable();
          enrolled_.remove(index);
          onChanged();
        } else {
          enrolledBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Student.SchoolSubject enrolled = 2;</code>
       */
      public com.mastercard.protobuf.StudentProto.Student.SchoolSubject.Builder getEnrolledBuilder(
          int index) {
        return getEnrolledFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Student.SchoolSubject enrolled = 2;</code>
       */
      public com.mastercard.protobuf.StudentProto.Student.SchoolSubjectOrBuilder getEnrolledOrBuilder(
          int index) {
        if (enrolledBuilder_ == null) {
          return enrolled_.get(index);  } else {
          return enrolledBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Student.SchoolSubject enrolled = 2;</code>
       */
      public java.util.List<? extends com.mastercard.protobuf.StudentProto.Student.SchoolSubjectOrBuilder> 
           getEnrolledOrBuilderList() {
        if (enrolledBuilder_ != null) {
          return enrolledBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(enrolled_);
        }
      }
      /**
       * <code>repeated .Student.SchoolSubject enrolled = 2;</code>
       */
      public com.mastercard.protobuf.StudentProto.Student.SchoolSubject.Builder addEnrolledBuilder() {
        return getEnrolledFieldBuilder().addBuilder(
            com.mastercard.protobuf.StudentProto.Student.SchoolSubject.getDefaultInstance());
      }
      /**
       * <code>repeated .Student.SchoolSubject enrolled = 2;</code>
       */
      public com.mastercard.protobuf.StudentProto.Student.SchoolSubject.Builder addEnrolledBuilder(
          int index) {
        return getEnrolledFieldBuilder().addBuilder(
            index, com.mastercard.protobuf.StudentProto.Student.SchoolSubject.getDefaultInstance());
      }
      /**
       * <code>repeated .Student.SchoolSubject enrolled = 2;</code>
       */
      public java.util.List<com.mastercard.protobuf.StudentProto.Student.SchoolSubject.Builder> 
           getEnrolledBuilderList() {
        return getEnrolledFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.mastercard.protobuf.StudentProto.Student.SchoolSubject, com.mastercard.protobuf.StudentProto.Student.SchoolSubject.Builder, com.mastercard.protobuf.StudentProto.Student.SchoolSubjectOrBuilder> 
          getEnrolledFieldBuilder() {
        if (enrolledBuilder_ == null) {
          enrolledBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.mastercard.protobuf.StudentProto.Student.SchoolSubject, com.mastercard.protobuf.StudentProto.Student.SchoolSubject.Builder, com.mastercard.protobuf.StudentProto.Student.SchoolSubjectOrBuilder>(
                  enrolled_,
                  ((bitField0_ & 0x00000002) != 0),
                  getParentForChildren(),
                  isClean());
          enrolled_ = null;
        }
        return enrolledBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Student)
    }

    // @@protoc_insertion_point(class_scope:Student)
    private static final com.mastercard.protobuf.StudentProto.Student DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.mastercard.protobuf.StudentProto.Student();
    }

    public static com.mastercard.protobuf.StudentProto.Student getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Student>
        PARSER = new com.google.protobuf.AbstractParser<Student>() {
      @java.lang.Override
      public Student parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Student(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Student> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Student> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.mastercard.protobuf.StudentProto.Student getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Student_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Student_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Student_SchoolSubject_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Student_SchoolSubject_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rstudent.proto\"t\n\007Student\022\r\n\005grade\030\001 \001(" +
      "\005\022(\n\010enrolled\030\002 \003(\0132\026.Student.SchoolSubj" +
      "ect\0320\n\rSchoolSubject\022\014\n\004name\030\001 \001(\t\022\021\n\tcl" +
      "assroom\030\002 \001(\005B\'\n\027com.mastercard.protobuf" +
      "B\014StudentProtob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Student_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Student_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Student_descriptor,
        new java.lang.String[] { "Grade", "Enrolled", });
    internal_static_Student_SchoolSubject_descriptor =
      internal_static_Student_descriptor.getNestedTypes().get(0);
    internal_static_Student_SchoolSubject_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Student_SchoolSubject_descriptor,
        new java.lang.String[] { "Name", "Classroom", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
