// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: teacher.proto

package com.mastercard.protobuf;

public final class TeacherProto {
  private TeacherProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface TeacherOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Teacher)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .Teacher.SchoolSubject teaching = 2;</code>
     */
    java.util.List<com.mastercard.protobuf.TeacherProto.Teacher.SchoolSubject> 
        getTeachingList();
    /**
     * <code>repeated .Teacher.SchoolSubject teaching = 2;</code>
     */
    com.mastercard.protobuf.TeacherProto.Teacher.SchoolSubject getTeaching(int index);
    /**
     * <code>repeated .Teacher.SchoolSubject teaching = 2;</code>
     */
    int getTeachingCount();
    /**
     * <code>repeated .Teacher.SchoolSubject teaching = 2;</code>
     */
    java.util.List<? extends com.mastercard.protobuf.TeacherProto.Teacher.SchoolSubjectOrBuilder> 
        getTeachingOrBuilderList();
    /**
     * <code>repeated .Teacher.SchoolSubject teaching = 2;</code>
     */
    com.mastercard.protobuf.TeacherProto.Teacher.SchoolSubjectOrBuilder getTeachingOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code Teacher}
   */
  public  static final class Teacher extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Teacher)
      TeacherOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Teacher.newBuilder() to construct.
    private Teacher(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Teacher() {
      teaching_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Teacher(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 18: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                teaching_ = new java.util.ArrayList<com.mastercard.protobuf.TeacherProto.Teacher.SchoolSubject>();
                mutable_bitField0_ |= 0x00000001;
              }
              teaching_.add(
                  input.readMessage(com.mastercard.protobuf.TeacherProto.Teacher.SchoolSubject.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          teaching_ = java.util.Collections.unmodifiableList(teaching_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.mastercard.protobuf.TeacherProto.internal_static_Teacher_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.mastercard.protobuf.TeacherProto.internal_static_Teacher_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.mastercard.protobuf.TeacherProto.Teacher.class, com.mastercard.protobuf.TeacherProto.Teacher.Builder.class);
    }

    public interface SchoolSubjectOrBuilder extends
        // @@protoc_insertion_point(interface_extends:Teacher.SchoolSubject)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>string name = 1;</code>
       */
      java.lang.String getName();
      /**
       * <code>string name = 1;</code>
       */
      com.google.protobuf.ByteString
          getNameBytes();

      /**
       * <code>int32 classroom = 2;</code>
       */
      int getClassroom();
    }
    /**
     * Protobuf type {@code Teacher.SchoolSubject}
     */
    public  static final class SchoolSubject extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:Teacher.SchoolSubject)
        SchoolSubjectOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use SchoolSubject.newBuilder() to construct.
      private SchoolSubject(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private SchoolSubject() {
        name_ = "";
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private SchoolSubject(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                java.lang.String s = input.readStringRequireUtf8();

                name_ = s;
                break;
              }
              case 16: {

                classroom_ = input.readInt32();
                break;
              }
              default: {
                if (!parseUnknownField(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.mastercard.protobuf.TeacherProto.internal_static_Teacher_SchoolSubject_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.mastercard.protobuf.TeacherProto.internal_static_Teacher_SchoolSubject_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.mastercard.protobuf.TeacherProto.Teacher.SchoolSubject.class, com.mastercard.protobuf.TeacherProto.Teacher.SchoolSubject.Builder.class);
      }

      public static final int NAME_FIELD_NUMBER = 1;
      private volatile java.lang.Object name_;
      /**
       * <code>string name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        }
      }
      /**
       * <code>string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int CLASSROOM_FIELD_NUMBER = 2;
      private int classroom_;
      /**
       * <code>int32 classroom = 2;</code>
       */
      public int getClassroom() {
        return classroom_;
      }

      private byte memoizedIsInitialized = -1;
      @java.lang.Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      @java.lang.Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (!getNameBytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
        }
        if (classroom_ != 0) {
          output.writeInt32(2, classroom_);
        }
        unknownFields.writeTo(output);
      }

      @java.lang.Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (!getNameBytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
        }
        if (classroom_ != 0) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(2, classroom_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof com.mastercard.protobuf.TeacherProto.Teacher.SchoolSubject)) {
          return super.equals(obj);
        }
        com.mastercard.protobuf.TeacherProto.Teacher.SchoolSubject other = (com.mastercard.protobuf.TeacherProto.Teacher.SchoolSubject) obj;

        if (!getName()
            .equals(other.getName())) return false;
        if (getClassroom()
            != other.getClassroom()) return false;
        if (!unknownFields.equals(other.unknownFields)) return false;
        return true;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + NAME_FIELD_NUMBER;
        hash = (53 * hash) + getName().hashCode();
        hash = (37 * hash) + CLASSROOM_FIELD_NUMBER;
        hash = (53 * hash) + getClassroom();
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static com.mastercard.protobuf.TeacherProto.Teacher.SchoolSubject parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.mastercard.protobuf.TeacherProto.Teacher.SchoolSubject parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.mastercard.protobuf.TeacherProto.Teacher.SchoolSubject parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.mastercard.protobuf.TeacherProto.Teacher.SchoolSubject parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.mastercard.protobuf.TeacherProto.Teacher.SchoolSubject parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.mastercard.protobuf.TeacherProto.Teacher.SchoolSubject parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.mastercard.protobuf.TeacherProto.Teacher.SchoolSubject parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static com.mastercard.protobuf.TeacherProto.Teacher.SchoolSubject parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static com.mastercard.protobuf.TeacherProto.Teacher.SchoolSubject parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static com.mastercard.protobuf.TeacherProto.Teacher.SchoolSubject parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static com.mastercard.protobuf.TeacherProto.Teacher.SchoolSubject parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static com.mastercard.protobuf.TeacherProto.Teacher.SchoolSubject parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @java.lang.Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(com.mastercard.protobuf.TeacherProto.Teacher.SchoolSubject prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @java.lang.Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code Teacher.SchoolSubject}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:Teacher.SchoolSubject)
          com.mastercard.protobuf.TeacherProto.Teacher.SchoolSubjectOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.mastercard.protobuf.TeacherProto.internal_static_Teacher_SchoolSubject_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.mastercard.protobuf.TeacherProto.internal_static_Teacher_SchoolSubject_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  com.mastercard.protobuf.TeacherProto.Teacher.SchoolSubject.class, com.mastercard.protobuf.TeacherProto.Teacher.SchoolSubject.Builder.class);
        }

        // Construct using com.mastercard.protobuf.TeacherProto.Teacher.SchoolSubject.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        @java.lang.Override
        public Builder clear() {
          super.clear();
          name_ = "";

          classroom_ = 0;

          return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.mastercard.protobuf.TeacherProto.internal_static_Teacher_SchoolSubject_descriptor;
        }

        @java.lang.Override
        public com.mastercard.protobuf.TeacherProto.Teacher.SchoolSubject getDefaultInstanceForType() {
          return com.mastercard.protobuf.TeacherProto.Teacher.SchoolSubject.getDefaultInstance();
        }

        @java.lang.Override
        public com.mastercard.protobuf.TeacherProto.Teacher.SchoolSubject build() {
          com.mastercard.protobuf.TeacherProto.Teacher.SchoolSubject result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @java.lang.Override
        public com.mastercard.protobuf.TeacherProto.Teacher.SchoolSubject buildPartial() {
          com.mastercard.protobuf.TeacherProto.Teacher.SchoolSubject result = new com.mastercard.protobuf.TeacherProto.Teacher.SchoolSubject(this);
          result.name_ = name_;
          result.classroom_ = classroom_;
          onBuilt();
          return result;
        }

        @java.lang.Override
        public Builder clone() {
          return super.clone();
        }
        @java.lang.Override
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.setField(field, value);
        }
        @java.lang.Override
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return super.clearField(field);
        }
        @java.lang.Override
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return super.clearOneof(oneof);
        }
        @java.lang.Override
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return super.setRepeatedField(field, index, value);
        }
        @java.lang.Override
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.addRepeatedField(field, value);
        }
        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.mastercard.protobuf.TeacherProto.Teacher.SchoolSubject) {
            return mergeFrom((com.mastercard.protobuf.TeacherProto.Teacher.SchoolSubject)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(com.mastercard.protobuf.TeacherProto.Teacher.SchoolSubject other) {
          if (other == com.mastercard.protobuf.TeacherProto.Teacher.SchoolSubject.getDefaultInstance()) return this;
          if (!other.getName().isEmpty()) {
            name_ = other.name_;
            onChanged();
          }
          if (other.getClassroom() != 0) {
            setClassroom(other.getClassroom());
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
          return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.mastercard.protobuf.TeacherProto.Teacher.SchoolSubject parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (com.mastercard.protobuf.TeacherProto.Teacher.SchoolSubject) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }

        private java.lang.Object name_ = "";
        /**
         * <code>string name = 1;</code>
         */
        public java.lang.String getName() {
          java.lang.Object ref = name_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            name_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>string name = 1;</code>
         */
        public com.google.protobuf.ByteString
            getNameBytes() {
          java.lang.Object ref = name_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            name_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string name = 1;</code>
         */
        public Builder setName(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          name_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>string name = 1;</code>
         */
        public Builder clearName() {
          
          name_ = getDefaultInstance().getName();
          onChanged();
          return this;
        }
        /**
         * <code>string name = 1;</code>
         */
        public Builder setNameBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          name_ = value;
          onChanged();
          return this;
        }

        private int classroom_ ;
        /**
         * <code>int32 classroom = 2;</code>
         */
        public int getClassroom() {
          return classroom_;
        }
        /**
         * <code>int32 classroom = 2;</code>
         */
        public Builder setClassroom(int value) {
          
          classroom_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>int32 classroom = 2;</code>
         */
        public Builder clearClassroom() {
          
          classroom_ = 0;
          onChanged();
          return this;
        }
        @java.lang.Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:Teacher.SchoolSubject)
      }

      // @@protoc_insertion_point(class_scope:Teacher.SchoolSubject)
      private static final com.mastercard.protobuf.TeacherProto.Teacher.SchoolSubject DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new com.mastercard.protobuf.TeacherProto.Teacher.SchoolSubject();
      }

      public static com.mastercard.protobuf.TeacherProto.Teacher.SchoolSubject getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<SchoolSubject>
          PARSER = new com.google.protobuf.AbstractParser<SchoolSubject>() {
        @java.lang.Override
        public SchoolSubject parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new SchoolSubject(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<SchoolSubject> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<SchoolSubject> getParserForType() {
        return PARSER;
      }

      @java.lang.Override
      public com.mastercard.protobuf.TeacherProto.Teacher.SchoolSubject getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    public static final int TEACHING_FIELD_NUMBER = 2;
    private java.util.List<com.mastercard.protobuf.TeacherProto.Teacher.SchoolSubject> teaching_;
    /**
     * <code>repeated .Teacher.SchoolSubject teaching = 2;</code>
     */
    public java.util.List<com.mastercard.protobuf.TeacherProto.Teacher.SchoolSubject> getTeachingList() {
      return teaching_;
    }
    /**
     * <code>repeated .Teacher.SchoolSubject teaching = 2;</code>
     */
    public java.util.List<? extends com.mastercard.protobuf.TeacherProto.Teacher.SchoolSubjectOrBuilder> 
        getTeachingOrBuilderList() {
      return teaching_;
    }
    /**
     * <code>repeated .Teacher.SchoolSubject teaching = 2;</code>
     */
    public int getTeachingCount() {
      return teaching_.size();
    }
    /**
     * <code>repeated .Teacher.SchoolSubject teaching = 2;</code>
     */
    public com.mastercard.protobuf.TeacherProto.Teacher.SchoolSubject getTeaching(int index) {
      return teaching_.get(index);
    }
    /**
     * <code>repeated .Teacher.SchoolSubject teaching = 2;</code>
     */
    public com.mastercard.protobuf.TeacherProto.Teacher.SchoolSubjectOrBuilder getTeachingOrBuilder(
        int index) {
      return teaching_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < teaching_.size(); i++) {
        output.writeMessage(2, teaching_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < teaching_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, teaching_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.mastercard.protobuf.TeacherProto.Teacher)) {
        return super.equals(obj);
      }
      com.mastercard.protobuf.TeacherProto.Teacher other = (com.mastercard.protobuf.TeacherProto.Teacher) obj;

      if (!getTeachingList()
          .equals(other.getTeachingList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getTeachingCount() > 0) {
        hash = (37 * hash) + TEACHING_FIELD_NUMBER;
        hash = (53 * hash) + getTeachingList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.mastercard.protobuf.TeacherProto.Teacher parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mastercard.protobuf.TeacherProto.Teacher parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mastercard.protobuf.TeacherProto.Teacher parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mastercard.protobuf.TeacherProto.Teacher parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mastercard.protobuf.TeacherProto.Teacher parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mastercard.protobuf.TeacherProto.Teacher parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mastercard.protobuf.TeacherProto.Teacher parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.mastercard.protobuf.TeacherProto.Teacher parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.mastercard.protobuf.TeacherProto.Teacher parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.mastercard.protobuf.TeacherProto.Teacher parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.mastercard.protobuf.TeacherProto.Teacher parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.mastercard.protobuf.TeacherProto.Teacher parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.mastercard.protobuf.TeacherProto.Teacher prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Teacher}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Teacher)
        com.mastercard.protobuf.TeacherProto.TeacherOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.mastercard.protobuf.TeacherProto.internal_static_Teacher_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.mastercard.protobuf.TeacherProto.internal_static_Teacher_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.mastercard.protobuf.TeacherProto.Teacher.class, com.mastercard.protobuf.TeacherProto.Teacher.Builder.class);
      }

      // Construct using com.mastercard.protobuf.TeacherProto.Teacher.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getTeachingFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (teachingBuilder_ == null) {
          teaching_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          teachingBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.mastercard.protobuf.TeacherProto.internal_static_Teacher_descriptor;
      }

      @java.lang.Override
      public com.mastercard.protobuf.TeacherProto.Teacher getDefaultInstanceForType() {
        return com.mastercard.protobuf.TeacherProto.Teacher.getDefaultInstance();
      }

      @java.lang.Override
      public com.mastercard.protobuf.TeacherProto.Teacher build() {
        com.mastercard.protobuf.TeacherProto.Teacher result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.mastercard.protobuf.TeacherProto.Teacher buildPartial() {
        com.mastercard.protobuf.TeacherProto.Teacher result = new com.mastercard.protobuf.TeacherProto.Teacher(this);
        int from_bitField0_ = bitField0_;
        if (teachingBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            teaching_ = java.util.Collections.unmodifiableList(teaching_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.teaching_ = teaching_;
        } else {
          result.teaching_ = teachingBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.mastercard.protobuf.TeacherProto.Teacher) {
          return mergeFrom((com.mastercard.protobuf.TeacherProto.Teacher)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.mastercard.protobuf.TeacherProto.Teacher other) {
        if (other == com.mastercard.protobuf.TeacherProto.Teacher.getDefaultInstance()) return this;
        if (teachingBuilder_ == null) {
          if (!other.teaching_.isEmpty()) {
            if (teaching_.isEmpty()) {
              teaching_ = other.teaching_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureTeachingIsMutable();
              teaching_.addAll(other.teaching_);
            }
            onChanged();
          }
        } else {
          if (!other.teaching_.isEmpty()) {
            if (teachingBuilder_.isEmpty()) {
              teachingBuilder_.dispose();
              teachingBuilder_ = null;
              teaching_ = other.teaching_;
              bitField0_ = (bitField0_ & ~0x00000001);
              teachingBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getTeachingFieldBuilder() : null;
            } else {
              teachingBuilder_.addAllMessages(other.teaching_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.mastercard.protobuf.TeacherProto.Teacher parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.mastercard.protobuf.TeacherProto.Teacher) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.mastercard.protobuf.TeacherProto.Teacher.SchoolSubject> teaching_ =
        java.util.Collections.emptyList();
      private void ensureTeachingIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          teaching_ = new java.util.ArrayList<com.mastercard.protobuf.TeacherProto.Teacher.SchoolSubject>(teaching_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.mastercard.protobuf.TeacherProto.Teacher.SchoolSubject, com.mastercard.protobuf.TeacherProto.Teacher.SchoolSubject.Builder, com.mastercard.protobuf.TeacherProto.Teacher.SchoolSubjectOrBuilder> teachingBuilder_;

      /**
       * <code>repeated .Teacher.SchoolSubject teaching = 2;</code>
       */
      public java.util.List<com.mastercard.protobuf.TeacherProto.Teacher.SchoolSubject> getTeachingList() {
        if (teachingBuilder_ == null) {
          return java.util.Collections.unmodifiableList(teaching_);
        } else {
          return teachingBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Teacher.SchoolSubject teaching = 2;</code>
       */
      public int getTeachingCount() {
        if (teachingBuilder_ == null) {
          return teaching_.size();
        } else {
          return teachingBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Teacher.SchoolSubject teaching = 2;</code>
       */
      public com.mastercard.protobuf.TeacherProto.Teacher.SchoolSubject getTeaching(int index) {
        if (teachingBuilder_ == null) {
          return teaching_.get(index);
        } else {
          return teachingBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Teacher.SchoolSubject teaching = 2;</code>
       */
      public Builder setTeaching(
          int index, com.mastercard.protobuf.TeacherProto.Teacher.SchoolSubject value) {
        if (teachingBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTeachingIsMutable();
          teaching_.set(index, value);
          onChanged();
        } else {
          teachingBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Teacher.SchoolSubject teaching = 2;</code>
       */
      public Builder setTeaching(
          int index, com.mastercard.protobuf.TeacherProto.Teacher.SchoolSubject.Builder builderForValue) {
        if (teachingBuilder_ == null) {
          ensureTeachingIsMutable();
          teaching_.set(index, builderForValue.build());
          onChanged();
        } else {
          teachingBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Teacher.SchoolSubject teaching = 2;</code>
       */
      public Builder addTeaching(com.mastercard.protobuf.TeacherProto.Teacher.SchoolSubject value) {
        if (teachingBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTeachingIsMutable();
          teaching_.add(value);
          onChanged();
        } else {
          teachingBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Teacher.SchoolSubject teaching = 2;</code>
       */
      public Builder addTeaching(
          int index, com.mastercard.protobuf.TeacherProto.Teacher.SchoolSubject value) {
        if (teachingBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTeachingIsMutable();
          teaching_.add(index, value);
          onChanged();
        } else {
          teachingBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Teacher.SchoolSubject teaching = 2;</code>
       */
      public Builder addTeaching(
          com.mastercard.protobuf.TeacherProto.Teacher.SchoolSubject.Builder builderForValue) {
        if (teachingBuilder_ == null) {
          ensureTeachingIsMutable();
          teaching_.add(builderForValue.build());
          onChanged();
        } else {
          teachingBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Teacher.SchoolSubject teaching = 2;</code>
       */
      public Builder addTeaching(
          int index, com.mastercard.protobuf.TeacherProto.Teacher.SchoolSubject.Builder builderForValue) {
        if (teachingBuilder_ == null) {
          ensureTeachingIsMutable();
          teaching_.add(index, builderForValue.build());
          onChanged();
        } else {
          teachingBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Teacher.SchoolSubject teaching = 2;</code>
       */
      public Builder addAllTeaching(
          java.lang.Iterable<? extends com.mastercard.protobuf.TeacherProto.Teacher.SchoolSubject> values) {
        if (teachingBuilder_ == null) {
          ensureTeachingIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, teaching_);
          onChanged();
        } else {
          teachingBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Teacher.SchoolSubject teaching = 2;</code>
       */
      public Builder clearTeaching() {
        if (teachingBuilder_ == null) {
          teaching_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          teachingBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Teacher.SchoolSubject teaching = 2;</code>
       */
      public Builder removeTeaching(int index) {
        if (teachingBuilder_ == null) {
          ensureTeachingIsMutable();
          teaching_.remove(index);
          onChanged();
        } else {
          teachingBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Teacher.SchoolSubject teaching = 2;</code>
       */
      public com.mastercard.protobuf.TeacherProto.Teacher.SchoolSubject.Builder getTeachingBuilder(
          int index) {
        return getTeachingFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Teacher.SchoolSubject teaching = 2;</code>
       */
      public com.mastercard.protobuf.TeacherProto.Teacher.SchoolSubjectOrBuilder getTeachingOrBuilder(
          int index) {
        if (teachingBuilder_ == null) {
          return teaching_.get(index);  } else {
          return teachingBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Teacher.SchoolSubject teaching = 2;</code>
       */
      public java.util.List<? extends com.mastercard.protobuf.TeacherProto.Teacher.SchoolSubjectOrBuilder> 
           getTeachingOrBuilderList() {
        if (teachingBuilder_ != null) {
          return teachingBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(teaching_);
        }
      }
      /**
       * <code>repeated .Teacher.SchoolSubject teaching = 2;</code>
       */
      public com.mastercard.protobuf.TeacherProto.Teacher.SchoolSubject.Builder addTeachingBuilder() {
        return getTeachingFieldBuilder().addBuilder(
            com.mastercard.protobuf.TeacherProto.Teacher.SchoolSubject.getDefaultInstance());
      }
      /**
       * <code>repeated .Teacher.SchoolSubject teaching = 2;</code>
       */
      public com.mastercard.protobuf.TeacherProto.Teacher.SchoolSubject.Builder addTeachingBuilder(
          int index) {
        return getTeachingFieldBuilder().addBuilder(
            index, com.mastercard.protobuf.TeacherProto.Teacher.SchoolSubject.getDefaultInstance());
      }
      /**
       * <code>repeated .Teacher.SchoolSubject teaching = 2;</code>
       */
      public java.util.List<com.mastercard.protobuf.TeacherProto.Teacher.SchoolSubject.Builder> 
           getTeachingBuilderList() {
        return getTeachingFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.mastercard.protobuf.TeacherProto.Teacher.SchoolSubject, com.mastercard.protobuf.TeacherProto.Teacher.SchoolSubject.Builder, com.mastercard.protobuf.TeacherProto.Teacher.SchoolSubjectOrBuilder> 
          getTeachingFieldBuilder() {
        if (teachingBuilder_ == null) {
          teachingBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.mastercard.protobuf.TeacherProto.Teacher.SchoolSubject, com.mastercard.protobuf.TeacherProto.Teacher.SchoolSubject.Builder, com.mastercard.protobuf.TeacherProto.Teacher.SchoolSubjectOrBuilder>(
                  teaching_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          teaching_ = null;
        }
        return teachingBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Teacher)
    }

    // @@protoc_insertion_point(class_scope:Teacher)
    private static final com.mastercard.protobuf.TeacherProto.Teacher DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.mastercard.protobuf.TeacherProto.Teacher();
    }

    public static com.mastercard.protobuf.TeacherProto.Teacher getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Teacher>
        PARSER = new com.google.protobuf.AbstractParser<Teacher>() {
      @java.lang.Override
      public Teacher parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Teacher(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Teacher> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Teacher> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.mastercard.protobuf.TeacherProto.Teacher getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Teacher_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Teacher_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Teacher_SchoolSubject_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Teacher_SchoolSubject_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rteacher.proto\"e\n\007Teacher\022(\n\010teaching\030\002" +
      " \003(\0132\026.Teacher.SchoolSubject\0320\n\rSchoolSu" +
      "bject\022\014\n\004name\030\001 \001(\t\022\021\n\tclassroom\030\002 \001(\005B\'" +
      "\n\027com.mastercard.protobufB\014TeacherProtob" +
      "\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Teacher_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Teacher_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Teacher_descriptor,
        new java.lang.String[] { "Teaching", });
    internal_static_Teacher_SchoolSubject_descriptor =
      internal_static_Teacher_descriptor.getNestedTypes().get(0);
    internal_static_Teacher_SchoolSubject_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Teacher_SchoolSubject_descriptor,
        new java.lang.String[] { "Name", "Classroom", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
